### ISSUE TITLE
UI looks bad with Unity theme

### ISSUE THREAD

**Issue by Grawl** [guileen/terminal-status#18]
Look at this:

![2014-05-19 15 46 01](https://cloud.githubusercontent.com/assets/846774/3010056/8be72538-df10-11e3-906d-b07d5bb47be9.png)

Looks bad. This is [Unity](https://github.com/orderedlist/unity-ui) theme on latest OS X.

**Comment by daverogers** [comment]
I've noticed it doesn't look that great in a few other themes as well. I'm assuming the theme editor needs to update their theme to be compatible. In the meantime, you could change this stuff via your styles.less file (*Atom > Open Your Stylesheet*), adding the following styles (default from repo), and updating however you want. You could contribute your changes upstream to the unity-ui theme as well.

```less
.cli-status {
  &.panel {
    margin-bottom: 0px;
    white-space: pre;
    word-wrap: break-word;
    font-size: 14px;
    font-family: monospace;
  }
  .panel-heading {
    // margin: 1px;
    padding: 2px;
    text-align: right;
    .btn {
      top: 0px;
    }
  }
  .terminal {
    // let's keep this as a fallback
    max-height: 300px;
    overflow-y: scroll;
    bottom: @component-padding;

    .file-info {
      width: 140px;
      display: inline-block;
      // height: 2.5em;
      float: left;
    }
    .stat-program {
      color: #26c26a;
    }
    .stat-link {
      color: hsl(285, 0.7, 0.7);
    }
    .clear {
      clear: both;
    }
  }
  .status-ignored {
    opacity: 0.5;
  }
  .status-running {
    color: hsl(180, 1, 0.5);
  }
  .status-info {
    color: hsl(220, 1, 0.5);
  }
  .status-success {
    color: hsl(100, 1, 0.5);
  }
  .status-error {
    color: hsl(0, 1, 0.5);
  }
}
```
src: https://github.com/guileen/terminal-status/blob/master/styles/cli-status.less
