### ISSUE TITLE
hidden files/directories leaking out of terminal window

### ISSUE THREAD

**Issue by ghost** [guileen/terminal-status#96]
See screenshot, and notice the `.gitignore`, `.apm`, `.node-gyp` files floating in the middle of my editor :(

<img width="1792" alt="screen shot 2015-08-10 at 1 35 49 pm" src="https://cloud.githubusercontent.com/assets/320562/9159945/e1f34eec-3f64-11e5-967f-d52b6fc46879.png">

**Comment by ghost** [comment]
Chrome rendering bug.  This fixes it:

``` css
.cli-status .terminal {
  transform: translate3d(0,0,0);
}
```
